---
language: python
python:
  - "python3-dev"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run ${PROJECT_NAME} sh -c "echo ---Wait for DB...--- && python3 manage.py wait_for_db && echo ---Make Migrations...--- && python3 manage.py migrate && echo ---Check for Superuser...--- && python3 manage.py cSU && echo ---Run the tests...--- && python3 manage.py wait_for_db && python3 manage.py test && flake8"
...
