---
services:
  collectible-app:
    container_name: collectible-app-api
    image: ${PYTHON_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - PYTHON_TAG=${PYTHON_TAG}
      - DB_HOST=db
      - DB_NAME=${PROJECT_NAME}-postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./${PROJECT_NAME}:/${PROJECT_NAME}
    command: >
      sh -c "echo ---Wait for DB...--- &&
        python3 manage.py wait_for_db &&
        echo ---Make Migrations...--- &&
        python3 manage.py migrate &&
        echo ---Check for Superuser...--- &&
        python3 manage.py cSU &&
        echo ---Run the server...--- &&
        python3 manage.py runserver 0.0.0.0:${DB_PORT_CONTAINER} &&
        echo ---Server launched.---"
    depends_on:
      - db
  db:
    image: "postgres:${POSTGRES_TAG}"
    container_name: ${PROJECT_NAME}-postgres
    environment:
      - POSTGRES_DB=${PROJECT_NAME}-postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_TAG=${POSTGRES_TAG}
      - DB_PORT_CONTAINER=${DB_PORT_CONTAINER}
      - DB_PORT_HOST=${DB_PORT_HOST}
    volumes:
      - ./${PROJECT_NAME}:/postgres
    stop_grace_period: 30s
...
